export const baseApi='https://api.themoviedb.org/3/'
export const API_KEY='72a5841ab03245e690c3c31bdcc868e0'
export const actionMovie='discover/movie?api_key=<<api_key>>&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&without_genres=28&with_watch_monetization_types=flatrate'
export const adventure='discover/movie?api_key=<<api_key>>&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&without_genres=12&with_watch_monetization_types=flatrate'
export const animation='discover/movie?api_key=<<api_key>>&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&without_genres=16&with_watch_monetization_types=flatrate'
export const comedy='discover/movie?api_key=<<api_key>>&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&without_genres=35&with_watch_monetization_types=flatrate'
export const drama='discover/movie?api_key=<<api_key>>&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&without_genres=18&with_watch_monetization_types=flatrate'
export const imageUrl='https://image.tmdb.org/t/p/w500/'